name: Build and Deploy to Azure Container Apps

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to ACR
      uses: azure/docker-login@v1
      with:
        login-server: demoacrmanojsingh.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push image
      run: |
        docker build -t demoacrmanojsingh.azurecr.io/hello-world-app:latest .
        docker push demoacrmanojsingh.azurecr.io/hello-world-app:latest

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        allow-no-subscriptions: true

    - name: Deploy to Azure Container App
      run: |
        az containerapp create \
          --name hello-world-app \
          --resource-group demoazuremanojsingh-resource-group \
          --environment demoazuremanojsingh-container-env \
          --image demoacrmanojsingh.azurecr.io/hello-world-app:latest \
          --target-port 80 \
          --ingress external \
          --registry-server demoacrmanojsingh.azurecr.io \
          --registry-username ${{ secrets.ACR_USERNAME }} \
          --registry-password ${{ secrets.ACR_PASSWORD }}
